'use strict';
const fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..');
const required=['main-v192.js','main-v191.js','lib/web-intelligence-refinements-v192.js','lib/web-intelligence-v191.js','src/conversation-tools-v192.js','src/index.html','src/app.js','package.json','nexa.project.json','scripts/test-v192-refinements.js'];
for(const file of required){const full=path.join(root,file);if(!fs.existsSync(full))throw new Error('Missing v1.9.2 dependency: '+file);const source=fs.readFileSync(full,'utf8');if(source.includes('<<<<<<<')||source.includes('>>>>>>>'))throw new Error('Conflict marker: '+file);}
const main=fs.readFileSync(path.join(root,'main-v192.js'),'utf8');for(const token of ["require('./main-v191.js')",'Refine.install(WebIntel)','conversation-tools-v192.js','store:get','loadFile('])if(!main.includes(token))throw new Error('main-v192 missing '+token);
const refinements=fs.readFileSync(path.join(root,'lib','web-intelligence-refinements-v192.js'),'utf8');for(const token of ['cleanInternalRefs','officialQueries','official-retry','publicResearchSystemMessage','citation:\'\'','Never expose','enhancedResearchForChat'])if(!refinements.includes(token))throw new Error('v1.9.2 web refinement missing '+token);
const conversations=fs.readFileSync(path.join(root,'src','conversation-tools-v192.js'),'utf8');for(const token of ['chat-rename-v192','Editar nombre de la conversación','data-rename-chat-v192','chatTitle','dispatchEvent(new Event(\'change\'','MutationObserver'])if(!conversations.includes(token))throw new Error('conversation rename integration missing '+token);
function requiresOf(file){if(!fs.existsSync(path.join(root,file)))return[];const src=fs.readFileSync(path.join(root,file),'utf8');return[...src.matchAll(/require\(['"]\.\/(main-v\d+\.js)['"]\)/g)].map(m=>m[1]);}
function chainsTo(start,target,seen=new Set()){if(start===target)return true;if(!start||seen.has(start)||!fs.existsSync(path.join(root,start)))return false;seen.add(start);return requiresOf(start).some(next=>chainsTo(next,target,seen));}
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));const entry=String(pkg.main||'');if(!entry||!chainsTo(entry,'main-v192.js'))throw new Error(`Current entry does not transitively chain to main-v192.js: ${entry}`);
for(const script of ['validate:v192','test:v192','validate:v191','test:v191'])if(!String(pkg.scripts?.[script]||'').trim())throw new Error('package scripts missing '+script);
if(!String(pkg.scripts.validate||'').includes('validate:v192')||!String(pkg.scripts.validate||'').includes('test:v192'))throw new Error('global validate does not include v1.9.2 checks');
const buildFiles=Array.isArray(pkg?.build?.files)?pkg.build.files.map(String):[];for(const file of ['main-v192.js','main-v191.js','main-v190.js','main-v189.js','main-v188.js','main.js','preload.js'])if(!buildFiles.includes(file))throw new Error('electron-builder missing '+file);
const project=JSON.parse(fs.readFileSync(path.join(root,'nexa.project.json'),'utf8'));const projectVersion=String(project.application_version||project.version||'');if(projectVersion!==String(pkg.version)||String(project.build||'')!==String(pkg.version))throw new Error(`nexa.project version/build mismatch: ${projectVersion} / ${project.build} vs ${pkg.version}`);
console.log('Nexa AI v1.9.2 Web Privacy + Official Retry + Conversation Rename validation: OK');
