'use strict';
const assert=require('node:assert/strict');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const pkg=JSON.parse(read('package.json'));
const project=JSON.parse(read('nexa.project.json'));
const main=read('main-v181.js');
const visual=require(path.join(root,'lib/visual-review-v181.js'));
assert.equal(pkg.version,'1.8.1');
assert.equal(pkg.main,'main-v181.js');
assert.ok(pkg.build.files.includes('main-v181.js'));
assert.ok(pkg.build.files.includes('main.js'));
assert.equal(project.version,'1.8.1');
for(const marker of ['ipcMain.handle = function','image:generate','visualGenerate','qwen2.5vl:3b','images:[base64]','num_gpu:0','renderRetry','V181.applyRepairs','require(\'./main.js\')']) assert.ok(main.includes(marker),marker);
const prompt='Crea un kanguro boxeador estilo cartoon, en pose dinámica, con guantes rojos, pero con encuadre muy cercano.';
const spec=visual.deriveVisualSpec(prompt);
assert.equal(spec.exact_subject_count,1); assert.equal(spec.requested_species,'kangaroo'); assert.equal(spec.requested_framing,'close');
assert.deepEqual(visual.targetDimensions(prompt),{width:896,height:896});
assert.match(visual.augmentInitialRequest(prompt),/exactly one main subject/i);
assert.match(visual.augmentInitialRequest(prompt),/long upright ears/i);
const bad=visual.finalizeEvaluation({subject_identity:'pass',subject_count:'fail',species_identity:'fail',requested_attributes:'pass',pose_action:'pass',style:'pass',framing:'pass',anatomy:'pass',background:'pass',text_integrity:'na',technical_quality:'pass',detected_subject_count:2,detected_subject:'boxers',detected_species:'unknown',confidence:.95,error_codes:[],problems:[],repair_positive:[],repair_negative:[]},prompt,86);
assert.equal(bad.pass,false); assert.ok(bad.error_codes.includes('E002')); assert.ok(bad.error_codes.includes('E008'));
const plan=visual.initialConstraints({positive_prompt:'cartoon character concept art',negative_prompt:'blurry',width:1024,height:768,steps:30,cfg:6,sampler_name:'euler',scheduler:'normal',style:'illustration'},prompt);
assert.doesNotMatch(plan.positive_prompt,/character concept art/i); assert.match(plan.negative_prompt,/character sheet/i);
const repaired=visual.applyRepairs(plan,bad,prompt,2); assert.match(repaired.positive_prompt,/unmistakable kangaroo anatomy/i); assert.match(repaired.negative_prompt,/wrong species/i);
for(const rel of ['main-v181.js','lib/visual-review-v181.js','package.json','nexa.project.json']){const body=read(rel);for(const token of ['<'.repeat(7),'='.repeat(7),'>'.repeat(7)]) assert.ok(!body.includes(token),rel+' conflict-like marker');}
console.log('Nexa AI v1.8.1 visual review validation: OK');
